afe_ip: 192.168.2.12
afe_port: 50000
sensors: # sensor name, block: A-E, channel: 1-4, gain: 0, 1, 2, 5, 10, 20, 50, 100
  - {label: "S01", block: "A", channel: "1", gain: 1}
  - {label: "S02", block: "A", channel: "2", gain: 2}
  - {label: "S03", block: "A", channel: "3", gain: 5}
  - {label: "S04", block: "A", channel: "4", gain: 10}
  - {label: "S05", block: "B", channel: "1", gain: 1}
  - {label: "S06", block: "B", channel: "2", gain: 1}
  - {label: "S07", block: "B", channel: "3", gain: 1}
  - {label: "S08", block: "B", channel: "4", gain: 1}
  - {label: "S09", block: "C", channel: "1", gain: 1}
  - {label: "S10", block: "C", channel: "2", gain: 1}
  - {label: "S11", block: "C", channel: "3", gain: 1}
  - {label: "S12", block: "C", channel: "4", gain: 1}
  - {label: "S13", block: "D", channel: "1", gain: 1}
  - {label: "S14", block: "D", channel: "2", gain: 1}
  - {label: "S15", block: "D", channel: "3", gain: 1}
  - {label: "S16", block: "D", channel: "4", gain: 1}
  - {label: "S17", block: "E", channel: "1", gain: 1}
  - {label: "S18", block: "E", channel: "2", gain: 1}
  - {label: "S19", block: "E", channel: "3", gain: 1}
  - {label: "S20", block: "E", channel: "4", gain: 1}
sampling_rate: 20000 # Hz
